kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  name: mysql
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-premium
  volumeMode: Filesystem
