kind: Secret
apiVersion: v1
metadata:
  name: cakephp-mysql-persistent
  labels:
    app: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
data:
  cakephp-secret-token: blRNSmNVdDhvbFN0RHVZTTVzM081cE0zZzBaUXRSanB5VHNaTnYxMHdHYkZlUnZOcEE=
  cakephp-security-salt: Z20wb2ZRa0hFdlFIaEFBcGZHOEFScEd5bXlqdm9FS3VFeGxXd0x2eA==
  database-password: cFdsUEpDNTZkMWZ4czZKRw==
  database-user: Y2FrZXBocA==
type: Opaque

